[2024-04-23T14:50:24.196+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T14:50:24.225+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:50:11.701399+00:00 [queued]>
[2024-04-23T14:50:24.238+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:50:11.701399+00:00 [queued]>
[2024-04-23T14:50:24.239+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T14:50:24.257+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-23 14:50:11.701399+00:00
[2024-04-23T14:50:24.268+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=581) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T14:50:24.271+0000] {standard_task_runner.py:63} INFO - Started process 590 to run task
[2024-04-23T14:50:24.271+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-23T14:50:11.701399+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpekbo05hm']
[2024-04-23T14:50:24.272+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask data_quality_check
[2024-04-23T14:50:24.337+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T14:50:11.701399+00:00 [running]> on host ec31c9b90297
[2024-04-23T14:50:24.457+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T14:50:11.701399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T14:50:11.701399+00:00'
[2024-04-23T14:50:24.460+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T14:50:24.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T14:50:24.463+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: data_quality_check() missing 1 required positional argument: 'df'
[2024-04-23T14:50:24.483+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240423T145011, start_date=20240423T145024, end_date=20240423T145024
[2024-04-23T14:50:24.504+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task data_quality_check (data_quality_check() missing 1 required positional argument: 'df'; 590)
[2024-04-23T14:50:24.528+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T14:50:24.556+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T14:50:24.559+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
