[2024-04-19T18:52:28.401+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T18:52:28.427+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.load_data manual__2024-04-19T18:52:24.961968+00:00 [queued]>
[2024-04-19T18:52:28.437+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.load_data manual__2024-04-19T18:52:24.961968+00:00 [queued]>
[2024-04-19T18:52:28.438+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-19T18:52:28.454+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-04-19 18:52:24.961968+00:00
[2024-04-19T18:52:28.464+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=571) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T18:52:28.466+0000] {standard_task_runner.py:63} INFO - Started process 580 to run task
[2024-04-19T18:52:28.466+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'load_data', 'manual__2024-04-19T18:52:24.961968+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpd4cjtyil']
[2024-04-19T18:52:28.468+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask load_data
[2024-04-19T18:52:28.530+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.load_data manual__2024-04-19T18:52:24.961968+00:00 [running]> on host ec31c9b90297
[2024-04-19T18:52:28.641+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T18:52:24.961968+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T18:52:24.961968+00:00'
[2024-04-19T18:52:28.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T18:52:28.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T18:52:28.648+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 22, in load_data
    df = pd.read_csv('airflow/dags/data/processed/final_data.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'airflow/dags/data/processed/final_data.csv'
[2024-04-19T18:52:28.662+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=load_data, execution_date=20240419T185224, start_date=20240419T185228, end_date=20240419T185228
[2024-04-19T18:52:28.680+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task load_data ([Errno 2] No such file or directory: 'airflow/dags/data/processed/final_data.csv'; 580)
[2024-04-19T18:52:28.724+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-19T18:52:28.760+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-19T18:52:28.763+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
