[2024-04-19T19:01:05.829+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T19:01:05.865+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-19T19:00:54.896237+00:00 [queued]>
[2024-04-19T19:01:05.877+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-19T19:00:54.896237+00:00 [queued]>
[2024-04-19T19:01:05.878+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-19T19:01:05.901+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_model> on 2024-04-19 19:00:54.896237+00:00
[2024-04-19T19:01:05.914+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T19:01:05.917+0000] {standard_task_runner.py:63} INFO - Started process 760 to run task
[2024-04-19T19:01:05.918+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'train_model', 'manual__2024-04-19T19:00:54.896237+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp9b968_g3']
[2024-04-19T19:01:05.921+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask train_model
[2024-04-19T19:01:05.991+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.train_model manual__2024-04-19T19:00:54.896237+00:00 [running]> on host ec31c9b90297
[2024-04-19T19:01:06.099+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T19:00:54.896237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T19:00:54.896237+00:00'
[2024-04-19T19:01:06.102+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T19:01:46.353+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-04-19T19:01:46.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-19T19:01:46.356+0000] {process_utils.py:132} INFO - Sending 15 to group 760. PIDs of all processes in the group: [760]
[2024-04-19T19:01:46.356+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 760
[2024-04-19T19:01:46.379+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-19T19:01:46.380+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T19:01:46.391+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 49, in train_model
    model.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/ensemble/_voting.py", line 366, in fit
    return super().fit(X, transformed_y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/ensemble/_voting.py", line 89, in fit
    self.estimators_ = Parallel(n_jobs=self.n_jobs)(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py", line 36, in _fit_single_estimator
    estimator.fit(X, y)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 489, in fit
    trees = Parallel(
            ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 192, in _parallel_build_trees
    tree._fit(
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/tree/_classes.py", line 472, in _fit
    builder.build(self.tree_, X, y, sample_weight, missing_values_in_feature_mask)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-19T19:01:46.411+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=model_pipeline, task_id=train_model, execution_date=20240419T190054, start_date=20240419T190105, end_date=20240419T190146
[2024-04-19T19:01:46.430+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task train_model ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(model_pipeline, train_model, manual__2024-04-19T19:00:54.896237+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'train_model', 'dag_id': 'model_pipeline', 'run_id': 'manual__2024-04-19T19:00:54.896237+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 19, 19, 1, 5, 866319, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 19, 19, 1, 46, 410851, tzinfo=Timezone('UTC')), 'duration': 40}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 760)
[2024-04-19T19:01:46.491+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=760, status='terminated', exitcode=1, started='19:01:05') (760) terminated with exit code 1
