[2024-04-30T16:21:46.517+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T16:21:46.552+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-30T16:18:07.815888+00:00 [queued]>
[2024-04-30T16:21:46.567+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-30T16:18:07.815888+00:00 [queued]>
[2024-04-30T16:21:46.568+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-30T16:21:46.594+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-04-30 16:18:07.815888+00:00
[2024-04-30T16:21:46.607+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T16:21:46.609+0000] {standard_task_runner.py:63} INFO - Started process 216 to run task
[2024-04-30T16:21:46.610+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'generate_report', 'manual__2024-04-30T16:18:07.815888+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmptilkt_nz']
[2024-04-30T16:21:46.612+0000] {standard_task_runner.py:91} INFO - Job 226: Subtask generate_report
[2024-04-30T16:21:46.680+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.generate_report manual__2024-04-30T16:18:07.815888+00:00 [running]> on host 3d39ed9c66c5
[2024-04-30T16:21:46.832+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T16:18:07.815888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T16:18:07.815888+00:00'
[2024-04-30T16:21:46.836+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T16:21:47.761+0000] {logging_mixin.py:188} WARNING - 2024/04/30 16:21:47 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-04-30T16:21:47.829+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T16:21:47.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T16:21:47.846+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=generate_report, execution_date=20240430T161807, start_date=20240430T162146, end_date=20240430T162147
[2024-04-30T16:21:47.915+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T16:21:47.964+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T16:21:47.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
