[2024-04-28T00:35:35.163+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T00:35:35.190+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-27T21:07:35.749013+00:00 [queued]>
[2024-04-28T00:35:35.200+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-27T21:07:35.749013+00:00 [queued]>
[2024-04-28T00:35:35.201+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-04-28T00:35:35.217+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_model> on 2024-04-27 21:07:35.749013+00:00
[2024-04-28T00:35:35.229+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T00:35:35.231+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-04-28T00:35:35.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'train_model', 'manual__2024-04-27T21:07:35.749013+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpb4k73n21']
[2024-04-28T00:35:35.233+0000] {standard_task_runner.py:91} INFO - Job 182: Subtask train_model
[2024-04-28T00:35:35.290+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.train_model manual__2024-04-27T21:07:35.749013+00:00 [running]> on host c4427bb7f712
[2024-04-28T00:35:36.285+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T21:07:35.749013+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T21:07:35.749013+00:00'
[2024-04-28T00:35:36.287+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T00:38:36.523+0000] {logging_mixin.py:188} WARNING - 2024/04/28 00:38:36 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-04-28T00:38:46.155+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

[2024-04-28T00:38:46.596+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-28T00:38:46.597+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T00:38:46.610+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=train_model, execution_date=20240427T210735, start_date=20240428T003535, end_date=20240428T003846
[2024-04-28T00:38:46.774+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T00:38:46.812+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-28T00:38:46.815+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
