[2024-04-23T15:36:11.508+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T15:36:11.541+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-23T15:32:59.793314+00:00 [queued]>
[2024-04-23T15:36:11.556+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-23T15:32:59.793314+00:00 [queued]>
[2024-04-23T15:36:11.557+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T15:36:11.577+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-04-23 15:32:59.793314+00:00
[2024-04-23T15:36:11.589+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1781) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T15:36:11.591+0000] {standard_task_runner.py:63} INFO - Started process 1790 to run task
[2024-04-23T15:36:11.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'generate_report', 'manual__2024-04-23T15:32:59.793314+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpgclrm7h5']
[2024-04-23T15:36:11.593+0000] {standard_task_runner.py:91} INFO - Job 132: Subtask generate_report
[2024-04-23T15:36:11.651+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.generate_report manual__2024-04-23T15:32:59.793314+00:00 [running]> on host ec31c9b90297
[2024-04-23T15:36:11.768+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T15:32:59.793314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T15:32:59.793314+00:00'
[2024-04-23T15:36:11.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T15:36:11.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T15:36:11.829+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 127, in generate_report
    with open(report_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/reporting/reporting/classification_report.txt'
[2024-04-23T15:36:11.841+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=generate_report, execution_date=20240423T153259, start_date=20240423T153611, end_date=20240423T153611
[2024-04-23T15:36:11.857+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 132 for task generate_report ([Errno 2] No such file or directory: '/opt/airflow/dags/reporting/reporting/classification_report.txt'; 1790)
[2024-04-23T15:36:11.888+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-23T15:36:11.916+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T15:36:11.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
