[2024-04-30T13:40:43.035+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T13:40:43.063+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-30T13:37:01.116508+00:00 [queued]>
[2024-04-30T13:40:43.074+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.generate_report manual__2024-04-30T13:37:01.116508+00:00 [queued]>
[2024-04-30T13:40:43.074+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-30T13:40:43.093+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-04-30 13:37:01.116508+00:00
[2024-04-30T13:40:43.105+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=416) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T13:40:43.107+0000] {standard_task_runner.py:63} INFO - Started process 425 to run task
[2024-04-30T13:40:43.108+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'generate_report', 'manual__2024-04-30T13:37:01.116508+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp77e3_hr4']
[2024-04-30T13:40:43.110+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask generate_report
[2024-04-30T13:40:43.169+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.generate_report manual__2024-04-30T13:37:01.116508+00:00 [running]> on host c4427bb7f712
[2024-04-30T13:40:43.293+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T13:37:01.116508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T13:37:01.116508+00:00'
[2024-04-30T13:40:43.295+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T13:40:44.140+0000] {logging_mixin.py:188} WARNING - 2024/04/30 13:40:44 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-04-30T13:40:44.157+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T13:40:44.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T13:40:44.170+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=generate_report, execution_date=20240430T133701, start_date=20240430T134043, end_date=20240430T134044
[2024-04-30T13:40:44.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T13:40:44.230+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T13:40:44.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
