[2024-04-19T19:26:05.916+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T19:26:05.946+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:22:55.884457+00:00 [queued]>
[2024-04-19T19:26:05.957+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:22:55.884457+00:00 [queued]>
[2024-04-19T19:26:05.958+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-19T19:26:05.975+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): evaluate_model> on 2024-04-19 19:22:55.884457+00:00
[2024-04-19T19:26:05.987+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1363) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T19:26:05.989+0000] {standard_task_runner.py:63} INFO - Started process 1372 to run task
[2024-04-19T19:26:05.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'evaluate_model', 'manual__2024-04-19T19:22:55.884457+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp73g2ea1c']
[2024-04-19T19:26:05.991+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask evaluate_model
[2024-04-19T19:26:06.053+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:22:55.884457+00:00 [running]> on host ec31c9b90297
[2024-04-19T19:26:06.170+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='evaluate_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T19:22:55.884457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T19:22:55.884457+00:00'
[2024-04-19T19:26:06.172+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T19:26:07.768+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

[2024-04-19T19:26:09.910+0000] {ml_pipeline_dag.py:74} INFO - Accuracy: 0.6409
Precision: 0.6259898864612156
Recall: 0.6679222233533544
F1 Score: 0.6462765957446809
[2024-04-19T19:26:09.950+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-19T19:26:09.951+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T19:26:09.962+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=evaluate_model, execution_date=20240419T192255, start_date=20240419T192605, end_date=20240419T192609
[2024-04-19T19:26:10.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-19T19:26:10.059+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-19T19:26:10.062+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
